### ISSUE TITLE
list() method from latest branch merge not included in latest npm install?

### ISSUE THREAD

**Issue by alanristic** [superfeedr/superfeedr-node#13]
I tried to investigate what went wrong, have no idea. 

package.json shows version 0.1.4, but the your list() method from latest branch merge is missing.

**Comment by julien51** [comment]
@alanristic Indeed, this is odd. I just pushed version 0.1.5. Let me know if that solves it.

**Comment by alanristic** [comment]
Jep, problem solved, tnx.
