### ISSUE TITLE
Implement Retrieving Entries with XMPP

### ISSUE THREAD

**Issue by millette** [superfeedr/superfeedr-node#19]
As documented at http://documentation.superfeedr.com/subscribers.html#retrievingentrieswithxmpp

**Comment by millette** [comment]
I might eventually take a stab at it, but I'm still wet behind my node and xmpp ears ;-)

**Comment by julien51** [comment]
It's on my TODO list as well... I just haven't found the time, but now that there's an open issue, it'll just be faster :)

**Comment by julien51** [comment]
Added to `superfeedr@0.2.0` in f689134b256583b2c5e8e335288528ca4144e79a
