### ISSUE TITLE
xmpp client confused by presence stanza?

### ISSUE THREAD

**Issue by millette** [superfeedr/superfeedr-node#20]
Around line 30 in superfeedr.js, I was getting an undefined error on getChild.

I did a very quick fix (no patch to submit) to breakout if psevent went undefined:

```
var psevent = stanza.getChild('event', 'http://jabber.org/protocol/pubsub#event');
if (!psevent) return;
```

On another note, I am now using a token :-)

**Comment by julien51** [comment]
@millette @jeanfw This indeed seems to be a bug in `superfeedr-node` related to our new XMPP server. Not sure why the previous one did not create trouble with the `<presence>` stanzas. Pushing a new version of the npm now: `superfeedr@0.1.8`
