### ISSUE TITLE
Missing properties in Subscribe callback

### ISSUE THREAD

**Issue by davepenfold** [superfeedr/superfeedr-node#24]
httpCode is NaN and and httpStatus is an empty string in the response object. I can also reproduce this in the XMPP console. Any ideas?

Thanks

**Comment by julien51** [comment]
@davepenfold Thanks for this. Do you mind sending a bit more details? What feed is this? Don't forget that this information is only available after we've fetched a new feed at least once. Once you subscribed, it sometimes take a couple minutes for us to do this as we prioritize existing feeds for which we expect to have received an update.

**Comment by davepenfold** [comment]
If this is intentional no problem, here's an example response object:

``` js
{
  url: 'https://itunes.apple.com/ca/rss/topaudiobooks/limit=25/xml',
  status: 'subscribed',
  title: '',
  httpCode: NaN,
  httpStatus: '',
  period: 4,
  nextFetch: 1238451905000,
  lastFetch: 1238451905000,
  lastParse: 1238451905000,
  lastMaintenance: 1215824721000 
}
```

It seems to be the default response for new feeds. I was expecting possibly to see a httpCode or httpStatus at minimum.

To generate the feed url I used this service: https://rss.itunes.apple.com

**Comment by julien51** [comment]
@davepenfold This is indeed the default values... we can't provide any HTTP status until we have actually fetched a feed :(
