### ISSUE TITLE
Missing feed title in subscription response

### ISSUE THREAD

**Issue by mborho** [superfeedr/superfeedr-node#3]
Sometimes following error happens when subscribing to a feed:

```
/path/to/node_modules/superfeedr/lib/ superfeedr.js:88
                       title: title.getText(),
                                    ^
TypeError: Cannot call method 'getText' of undefined
```

**Comment by superfeedr** [comment]
Martin, I just pushed an update, but it's rather ugly :/ My JS mojo is far from being that good... Feel free to check the commit and refactor if you can do something nicer!

**Comment by mborho** [comment]
"git push" ? :)

**Comment by superfeedr** [comment]
:) Fixed!
