### ISSUE TITLE
0.0.5: no entries in notification

### ISSUE THREAD

**Issue by mborho** [superfeedr/superfeedr-node#7]
Hi,

it seems that 0.0.5 has stopped to expose items to the notification event at all.  At least dummy.xml doesn't work anymore.

Greetings 
Martin

**Comment by superfeedr** [comment]
Any idea of what could be wrong? What is the format you're using for your subscriptions? ATOM or JSON?

**Comment by superfeedr** [comment]
Martin, I am quite puzzled, because I just did tests using both json and atom, and they both worked. If would really help if you could tell me more on what exactly is failing.

**Comment by mborho** [comment]
I'm using json and I guess that the point.

Using basic.js example and triggering dummy.xml in the xmpp console on superfeedr.com the "notification.entries" array is empty on "notification" event. (notification.feed is there)

{ feed: 
   { url: 'http://superfeedr.com/dummy.xml',
     title: 'The Dummy Time Feed',
     httpCode: 200,
     httpStatus: '7452B in 0.065089192s, 1/10 new entries',
     period: 900,
     nextFetch: 1332611325000,
     lastFetch: 1332610436000,
     lastParse: 1332610436000,
     lastMaintenance: 1332537123000 },
  entries: [] }
